services:
  postgres:
    container_name: steam-inventory-pg
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", $POSTGRES_USER, "-d", $POSTGRES_DB]
      interval: 10s
      timeout: 5s
      start_period: 2s
      retries: 5
    env_file: .env

volumes:
  pg:
